version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: productfrontend
    ports:
      - "2020:2020"
    volumes:
      - ./app:/app
    environment:
      NODE_ENV: development
    tty: true