version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: docker/dockerfile
    container_name: productfrontend
    ports:
      - "2020:2020"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENG= development
    tty: true